THISPKG	= polyparse
VERSION = 1.1
SEARCH	= -package base
EXTRA_H_FLAGS   = -K6M -DVERSION=$(VERSION)
EXTRA_HBC_FLAGS = -H50M -A4M

DIRS	= \
	Text Text/ParserCombinators Text/ParserCombinators/Poly \
	Text/ParserCombinators/Poly/NoLeak

SRCS	= \
	Text/ParserCombinators/HuttonMeijer.hs \
	Text/ParserCombinators/HuttonMeijerWallace.hs \
	Text/ParserCombinators/Poly.hs \
	Text/ParserCombinators/PolyState.hs \
	Text/ParserCombinators/PolyLazy.hs \
	Text/ParserCombinators/PolyStateLazy.hs \
        Text/ParserCombinators/Poly/Base.hs \
        Text/ParserCombinators/Poly/Plain.hs \
        Text/ParserCombinators/Poly/Lazy.hs \
        Text/ParserCombinators/Poly/State.hs \
        Text/ParserCombinators/Poly/StateLazy.hs \
        Text/ParserCombinators/Poly/NoLeak/Plain.hs \
        Text/ParserCombinators/Poly/NoLeak/Lazy.hs \
        Text/ParserCombinators/Poly/NoLeak/State.hs \
        Text/ParserCombinators/Poly/NoLeak/StateLazy.hs \
	Text/Parse.hs \


# Here are the main rules.
include ../../Makefile.common

# extra rules

# Here are any extra dependencies.

# C-files dependencies.

